### ISSUE TITLE
Unable to build image 6.3

### ISSUE THREAD

**Issue by mickd5** [openatv/enigma2#1342]
Unable to build 6.3 image. 
**From Console log**
ERROR: Failed to spawn fakeroot worker to run /home/openatvbuilder/openatvARM6.3/build-enviroment/meta-oe-alliance/meta-oe/recipes-kernel/linux-libc-headers/linux-libc-headers_4.18.bb:do_install: [Errno 32] Broken pipe

**From bitbake-cooker-daemon log**
Running command ['buildTargets', ['openatv-image'], 'build']
Traceback (most recent call last):
  File "/home/openatvbuilder/openatvARM6.3/build-enviroment/bitbake/bin/bitbake-worker", line 7, in <module>
    from bb import fetch2
  File "/home/openatvbuilder/openatvARM6.3/build-enviroment/bitbake/lib/bb/__init__.py", line 83, in <module>
    from bb import fetch2 as fetch
  File "/home/openatvbuilder/openatvARM6.3/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 31, in <module>
    import urllib.request, urllib.parse, urllib.error
  File "/usr/lib/python3.5/urllib/request.py", line 88, in <module>
    import http.client
  File "/usr/lib/python3.5/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.5/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.5/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib/python3.5/email/message.py", line 16, in <module>
    from email import utils
  File "/usr/lib/python3.5/email/utils.py", line 30, in <module>
    import datetime
  File "/usr/lib/python3.5/datetime.py", line 636, in <module>
    timedelta.min = timedelta(-999999999)
  File "/usr/lib/python3.5/datetime.py", line 413, in __new__
    microseconds = round(microseconds + usdouble)
ValueError: cannot convert float NaN to integer
Connecting Client
Disconnecting Client
No timeout, exiting.
Exiting

Running Ubuntu 16.04.6 LTS 32bit . Any help with the above error greatly appreciated. Have built 6.2 image previously without any issues.

**Comment by atvcaptain** [comment]
we never use ubunto 16_04 32 bit

you can use 16_04  64 , better use now ubunto 18_04 lts 64 bit

**Comment by mickd5** [comment]
The issue seems to be caused datetime.py in python 3.5. It causes bitbake to crash and results in the broken pipe. Python 3.6 doesn't seem to cause any issue which comes as default with Ubuntu 18.04.
