### ISSUE TITLE
OpenATV 6.3 (26-05-2020) Crashing

### ISSUE THREAD

**Issue by ozone1864** [openatv/enigma2#1672]
Dear @arn354 ,
OpenATV is crashing with bluescreen again but with another error today after usage
of many plugins like youtube by taapat and e2iplayer.
As seen problem with mytest.py and Task.py
Please check attached logs.
Regards,
[enigma2_crash_1590488006.log](https://github.com/openatv/enigma2/files/4681848/enigma2_crash_1590488006.log)
[enigma2_crash_1590492073.log](https://github.com/openatv/enigma2/files/4681849/enigma2_crash_1590492073.log)

**Comment by arn354** [comment]
```
13:13:26.2884 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 13:13:26+0300 [-]   File "/home/oe1/atv63/build-enviroment/builds/openatv/release/h9/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-youtube/gitAUTOINC+1f8bc35b17-r0/git/src/YouTubeDownload.py", line 182, in updateDownloadList
13:13:26.2888 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 13:13:26+0300 [-]   File "/usr/lib/enigma2/python/Components/Task.py", line 35, in getProgress
13:13:26.2894 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 13:13:26+0300 [-] IndexError: list index out of range
```

no idea why call of getProgress causes a IndexError. see no difference to openpli Task.py .

```
14:21:13.8536 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 14:21:13+0300 [-] [SCREENNAME]  E2iPlayerWidget
14:21:13.8550 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 14:21:13+0300 [-] Traceback (most recent call last):
14:21:13.8556 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 14:21:13+0300 [-]   File "/usr/lib/enigma2/python/mytest.py", line 252, in processDelay
14:21:13.8565 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 14:21:13+0300 [-]     callback(*retval)
14:21:13.8574 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-05-26 14:21:13+0300 [-] TypeError: leaveArticleView() takes exactly 1 argument (2 given)
```

also see no difference to openpli in mytest.py in def processDelay(self)

**Comment by ozone1864** [comment]
@Taapat check please

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/commit/14fec2912b73efd7104859203e2042461d1b1b2e
