### ISSUE TITLE
Starting a `Record` causes bluescreen (OpenATV 6.5, 7.0) 

### ISSUE THREAD

**Issue by wedebe** [openatv/enigma2#1945]
Pressing the record button and a subsequent option (event/duration/indefinitely/etc.) causes a bluescreen with 
`[eDVBPESReader] Created. Opening demux`

I've attached a log.
[enigma2_crash_1623059392.log](https://github.com/openatv/enigma2/files/6607867/enigma2_crash_1623059392.log)

Mut@nt HD51 with 6.5 image from 2021-06-06
This is a long-running issue, I have never been able to record using 6.5 and have to boot into OpenATV 6.4 to do so.

**Comment by jbleyel** [comment]
VU Solo4K / OpenATV 7.0 (current git)
* Press Red button
* select 1,2,3,4, -> timer created and recording

**Comment by jbleyel** [comment]
Hi @wedebe , please try again using the latest build of OpenATV 7.0.

**Comment by wedebe** [comment]
OpenATV 7.0 still crashes on record 😔

[enigma2_crash_1623747780.log](https://github.com/openatv/enigma2/files/6655274/enigma2_crash_1623747780.log)

**Comment by jbleyel** [comment]
Please connect to the box via SSH/Telnet.
```
init 5
enigma2

```

Then reproduce the crash.
Then provide the last part of the console output because the crashlog do not include any useful info.

**Comment by wedebe** [comment]
```
[eRCDeviceInputDev] 1 a7 1
2021-06-15 18:59:46+0100 [-] [InfoBarGenerics] KEY: 167 0 KEY_RECORD RECORD
[eRCDeviceInputDev] 0 a7 1
2021-06-15 18:59:46+0100 [-] [InfoBarGenerics] KEY: 167 1 KEY_RECORD RECORD
m_dvbid:1 m_slotid:1 type:0 types:1 m_enabled:0
[eDVBFrontend] opening frontend 0
m_dvbid:1 m_slotid:1 type:0 types:1 m_enabled:0
2021-06-15 18:59:46+0100 [-] [Timer] Record RecordTimerEntry(name=Dogs Behaving (Very) Badly, begin=Tue Jun 15 18:59:46 2021, end=Wed Jun 16 18:59:46 2021, serviceref=1:0:1:1E25:809:2:11A0000:0:0:0:, justplay=False, isAutoTimer=False)
2021-06-15 18:59:46+0100 [-] starting thread :writeable
2021-06-15 18:59:46+0100 [-] finished thread :writeable
2021-06-15 18:59:46+0100 [-] starting thread :freespace
2021-06-15 18:59:46+0100 [-] finished thread :freespace
2021-06-15 18:59:46+0100 [-] Traceback (most recent call last):
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/Screens/ButtonSetup.py", line 530, in action
2021-06-15 18:59:46+0100 [-]     res = self.actions[action](action)
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/Screens/ButtonSetup.py", line 584, in ButtonSetupGlobal
2021-06-15 18:59:46+0100 [-]     return self.execButtonSetup(selected[0])
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/Screens/ButtonSetup.py", line 626, in execButtonSetup
2021-06-15 18:59:46+0100 [-]     exec("self." + ".".join(selected[1:]) + "()")
2021-06-15 18:59:46+0100 [-]   File "<string>", line 1, in <module>
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3956, in startInstantRecording
2021-06-15 18:59:46+0100 [-]     simulTimerList = self.session.nav.RecordTimer.record(recording)
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/RecordTimer.py", line 1484, in record
2021-06-15 18:59:46+0100 [-]     self.addTimerEntry(entry)
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/timer.py", line 203, in addTimerEntry
2021-06-15 18:59:46+0100 [-]     self.calcNextActivation()
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/timer.py", line 242, in calcNextActivation
2021-06-15 18:59:46+0100 [-]     self.processActivation()
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/timer.py", line 313, in processActivation
2021-06-15 18:59:46+0100 [-]     self.doActivate(self.timer_list[0])
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/RecordTimer.py", line 1250, in doActivate
2021-06-15 18:59:46+0100 [-]     if w.activate():
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/RecordTimer.py", line 520, in activate
2021-06-15 18:59:46+0100 [-]     if self.tryPrepare():
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/RecordTimer.py", line 375, in tryPrepare
2021-06-15 18:59:46+0100 [-]     if not self.calculateFilename():
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/RecordTimer.py", line 351, in calculateFilename
2021-06-15 18:59:46+0100 [-]     filename = ASCIItranslit.legacyEncode(filename)
2021-06-15 18:59:46+0100 [-]   File "/usr/lib/enigma2/python/Tools/ASCIItranslit.py", line 276, in legacyEncode
2021-06-15 18:59:46+0100 [-]     string2 = string2.decode("utf-8")
2021-06-15 18:59:46+0100 [-] AttributeError: 'str' object has no attribute 'decode'
[ePyObject] (PyObject_CallObject(<bound method helpableButtonSetupActionMap.action of <Screens.ButtonSetup.helpableButtonSetupActionMap object at 0xb0b69820>>,('ButtonSetupActions', 'rec')) failed)
[gRC] main thread is non-idle! display spinner!
2021-06-15 18:59:56+0100 [-] [ActionMap] Keymap(s) 'MsgBoxActions, DirectionActions' -> Undefined action(s) 'ok, up, left'.
2021-06-15 18:59:56+0100 [-] [Skin] Processing screen 'MessageBox', position=(240, 160), size=(800 x 400) for module 'MessageBox'.
2021-06-15 18:59:56+0100 [-] StackTrace
2021-06-15 18:59:56+0100 [-] [Screen] Warning: Skin is missing element 'icon' in <class 'Screens.MessageBox.MessageBox'>(Your receiver has experienced a software problem
2021-06-15 18:59:56+0100 [-] which has occurred 1 times since the last restart.
2021-06-15 18:59:56+0100 [-] (Your receiver will automatically restart after 3 crashes).
2021-06-15 18:59:56+0100 [-] --------------------------------------------------------------------------------
2021-06-15 18:59:56+0100 [-] A crash log has been saved  to /home/root/logs/).
2021-06-15 18:59:56+0100 [-] setPixmapNum(3) failed! defined pixmaps: []
2021-06-15 18:59:56+0100 [-] [Skin] Processing screen 'MessageBox_summary' from list 'MessageBox_summary, SimpleSummary', position=(0, 0), size=(132 x 64) for module 'SimpleSummary'.
2021-06-15 18:59:56+0100 [-] [Screen] Showing screen '['MessageBox_summary', 'SimpleSummary']'.
2021-06-15 18:59:56+0100 [-] [Screen] Showing screen '['MessageBox']'.
2021-06-15 18:59:56+0100 [-] [Volume Adjust] Update Info
2021-06-15 18:59:56+0100 [-] [Volume Adjust] Volume = 90
2021-06-15 18:59:56+0100 [-] [Volume Adjust] load xml...
2021-06-15 18:59:56+0100 [-] "::ffff:192.168.43.154" - - [15/Jun/2021:17:59:30 +0000] "GET /api/statusinfo HTTP/1.1" 200 411 "http://192.168.43.147/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
2021-06-15 18:59:56+0100 [-] "::ffff:192.168.43.154" - - [15/Jun/2021:17:59:56 +0000] "GET /api/statusinfo HTTP/1.1" 200 411 "http://192.168.43.147/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
2021-06-15 18:59:56+0100 [-] "::ffff:192.168.43.154" - - [15/Jun/2021:17:59:56 +0000] "GET /api/statusinfo HTTP/1.1" 200 411 "http://192.168.43.147/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
2021-06-15 18:59:56+0100 [-] ========== Stacktrace of active Python threads ===========
2021-06-15 18:59:56+0100 [-] ========== Thread ID  0xb03ad390 =========================
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
2021-06-15 18:59:56+0100 [-]   self._bootstrap_inner()
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2021-06-15 18:59:56+0100 [-]   self.run()
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/threading.py", line 892, in run
2021-06-15 18:59:56+0100 [-]   self._target(*self._args, **self._kwargs)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/site-packages/twisted/_threads/_threadworker.py", line 46, in work
2021-06-15 18:59:56+0100 [-]   for task in iter(queue.get, _stop):
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/queue.py", line 171, in get
2021-06-15 18:59:56+0100 [-]   self.not_empty.wait()
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/threading.py", line 312, in wait
2021-06-15 18:59:56+0100 [-]   waiter.acquire()
2021-06-15 18:59:56+0100 [-] ========== MainThread 0xb6f2fb80 =========================
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 914, in <module>
2021-06-15 18:59:56+0100 [-]   runScreenTest()
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 680, in runScreenTest
2021-06-15 18:59:56+0100 [-]   runReactor()
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 144, in runReactor
2021-06-15 18:59:56+0100 [-]   reactor.run(installSignalHandlers=False)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/site-packages/twisted/internet/base.py", line 1423, in run
2021-06-15 18:59:56+0100 [-]   self.mainLoop()
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/site-packages/twisted/internet/base.py", line 1436, in mainLoop
2021-06-15 18:59:56+0100 [-]   reactorBaseSelf.doIteration(t)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/e2reactor.py", line 156, in doPoll
2021-06-15 18:59:56+0100 [-]   l = poller.poll(timeout)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/e2reactor.py", line 45, in poll
2021-06-15 18:59:56+0100 [-]   r = self.eApp.poll(timeout, self.dict)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 5479, in checkBsodCallback
2021-06-15 18:59:56+0100 [-]   self.lastBsod = bsodcnt
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 353, in openWithCallback
2021-06-15 18:59:56+0100 [-]   return dlg
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 373, in open
2021-06-15 18:59:56+0100 [-]   return dlg
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 298, in instantiateDialog
2021-06-15 18:59:56+0100 [-]   return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/mytest.py", line 328, in doInstantiateDialog
2021-06-15 18:59:56+0100 [-]   return dlg
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/skin.py", line 1249, in readSkin
2021-06-15 18:59:56+0100 [-]   usedComponents = None
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/skin.py", line 1197, in processScreen
2021-06-15 18:59:56+0100 [-]   print("[Skin] Error in screen '%s' widget '%s' %s!" % (name, w.tag, str(err)))
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/skin.py", line 1217, in processPanel
2021-06-15 18:59:56+0100 [-]   processScreen(widget, c)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/skin.py", line 1197, in processScreen
2021-06-15 18:59:56+0100 [-]   print("[Skin] Error in screen '%s' widget '%s' %s!" % (name, w.tag, str(err)))
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/skin.py", line 1155, in processWidget
2021-06-15 18:59:56+0100 [-]   screen.renderer.append(renderer)
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/skin.py", line 442, in collectAttributes
2021-06-15 18:59:56+0100 [-]   skinAttributes.append(("size", size))
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/enigma2/python/Tools/Directories.py", line 219, in resolveFilename
2021-06-15 18:59:56+0100 [-]   return path
2021-06-15 18:59:56+0100 [-] File: "/usr/lib/python3.9/genericpath.py", line 22, in exists
2021-06-15 18:59:56+0100 [-]   return True
2021-06-15 18:59:56+0100 [-] ========== Stacktrace end ================================
```

**Comment by jbleyel** [comment]
This setting is a problem.

config.recording.ascii_filenames = True

I will check this.

**Comment by wedebe** [comment]
> This setting is a problem.
> 
> config.recording.ascii_filenames = True
> 
> I will check this.

I cxan confirm setting `config.recording.ascii_filenames=false` allows recording without a crash :)
