### ISSUE TITLE
Positioner Setup crash

### ISSUE THREAD

**Issue by AbuBaniaz** [openatv/enigma2#2485]
A user on one of the UK forums has posted a crash when using Positioner setup.

```
20:04:37.7790 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-] getRawChannel failed
20:04:37.7796 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-] getRawChannel failed
20:04:37.7831 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-] [Screen] Showing screen 'QuickMenu'.
20:04:37.7841 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-] Traceback (most recent call last):
20:04:37.7851 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
20:04:37.7860 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/Infopanel/QuickMenu.py", line 383, in ok
20:04:37.7867 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/Infopanel/QuickMenu.py", line 514, in okSubList
20:04:37.7871 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/Infopanel/QuickMenu.py", line 617, in PositionerMain
20:04:37.7876 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/mytest.py", line 359, in open
20:04:37.7883 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
20:04:37.7887 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/mytest.py", line 294, in instantiateDialog
20:04:37.7893 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
20:04:37.7897 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/mytest.py", line 316, in doInstantiateDialog
20:04:37.7902 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]     dlg = screen(self, *arguments, **kwargs)
20:04:37.7906 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/PositionerSetup/plugin.py", line 161, in __init__
20:04:37.7912 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/PositionerSetup/plugin.py", line 650, in tuningChangedTo
20:04:37.7916 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-]   File "/usr/lib/enigma2/python/Tools/Transponder.py", line 99, in ConvertToHumanReadable
20:04:37.7922 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2022-08-15 20:04:37+0100 [-] TypeError: int() argument must be a string or a number, not 'NoneType'
20:04:37.7924 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0xac4ae2d8>>,('SetupActions', 'ok')) failed)
```
One of the posts on forum says that image date is 2022.07.15.
```
https://www.techkings.org/threads/motor-crashing-past-30e.168550/
```

[enigma2_crash_1660590277.txt](https://github.com/openatv/enigma2/files/9401099/enigma2_crash_1660590277.txt)

**Comment by wedebe** [comment]
Probably safe to suggest whether they've tried and still get the issue with the most recent image? The version being used is a month out of date.

**Comment by AbuBaniaz** [comment]
The affected files have not changed as far as I can tell. Anyway, I doubt he will test it. I asked him to just test selecting channels without going into other menus, yet he still deletes the channels on 39e and 42s and rescans. He said that his motor was locking up. I am not sure if this was the same issue where it fails to convert the signal data and then locks up or something else.

I'll close the issue as we are unlikely to get further testing from the affected person.
