### ISSUE TITLE
EPGRefresh Crash (Low priority)

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3035]
Bekomme diesen Crash wenn EPGRefresh läuft. Vielleicht mag sich das mal einer Ansehen...
Tritt nicht erst seit kurzem auf. Ich nehme an, dass es nicht direkt an EPGRefresh liegt, sonst würde ich es dort melden!

Nachstellen:

- EPGRefresh -> Einstellung -> Aktualisierung unter Verwendung von -> "Bild im Bild" oder "Bild im Bild(versteckt)"
- EPGRefresh -> **Aktualisierung starten**
- **Taste 0 für zurück zum letzten Sender**

```
10:48:35.5510 Traceback (most recent call last):
10:48:35.5511   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 301, in action
10:48:35.5524     response = self.actions[action](int(action))
10:48:35.5531                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10:48:35.5532   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1224, in keyNumberGlobal
10:48:35.5557     self.pipDoHandle0Action()
10:48:35.5560   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3645, in pipDoHandle0Action
10:48:35.5615     self.swapPiP()
10:48:35.5620   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3628, in swapPiP
10:48:35.5681     self.servicelist.setCurrentServicePath(self.session.pip.servicePath, doZap=False)
10:48:35.5685   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2571, in setCurrentServicePath
10:48:35.5731     self.setHistoryPath(doZap)
10:48:35.5734   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2455, in setHistoryPath
10:48:35.5773     ref = path.pop()
10:48:35.5776           ^^^^^^^^
10:48:35.5780 AttributeError: 'str' object has no attribute 'pop'
10:48:35.5781 [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0xb0720470>>,('NumberActions', '0')) failed)
```

Manchmal kommt es auch noch zu einem weiteren Crash
```
            ............               self.history[self.history_pos][-1] != currentPlayedRef:
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: string index out of range)
```

zBsp.:
```
11:00:30.5367 Traceback (most recent call last):
11:00:30.5368   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 301, in action
11:00:30.5376     response = self.actions[action](int(action))
11:00:30.5381                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:00:30.5381   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1226, in keyNumberGlobal
11:00:30.5401     self.checkTimeshiftRunning(self.recallPrevService)
11:00:30.5403   File "/usr/lib/enigma2/python/Components/Timeshift.py", line 504, in checkTimeshiftRunning
11:00:30.5421     returnFunction(True)
11:00:30.5423   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1282, in recallPrevService
11:00:30.5444     self.servicelist.recallPrevService()
11:00:30.5446   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2581, in recallPrevService
11:00:30.5486     if hlen > 0 and currentPlayedRef and self.history[self.history_pos][-1] != currentPlayedRef:
11:00:30.5492                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
11:00:30.5493 IndexError: string index out of range
11:00:30.5493 [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0xb0720470>>,('NumberActions', '0')) failed)
```

**Comment by jbleyel** [comment]
This will be difficult. As long as the refresh is running, nothing else should be done.
Or does this also happen after the refresh is finished?

**Comment by GhostofGeeeee** [comment]
I noticed it while running refresh.
Ich glaube da mir war da gar nicht bewusst, dass die "Taste 0" in dem Moment eine andere Funktion bekommt(zwischen PIP wechseln). 
Wenn man zumindest den Crash abfangen könnte!

**Comment by Papi2000-new** [comment]
By the way:
The preferred method to be used for refresh should be "Pseudo recording". That method is the way, the software in the past was rewritten / updated and debuged. That also means for example: only use each trnsponder once for all services in a list, and skip other services on allready checked transponders.

**Comment by GhostofGeeeee** [comment]
Good that you say it again(i read it on forum).
On start using EPGRefresh I decided to don't use "Pseudo recording", now I will change and close this and I hope I haven't to create another issue.
Thank you both.
