### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GhostofGeeeee** [openatv/enigma2#3185]
I have a old crash, I think, it's not fixed now.
```
[Enigma] Python path is '/usr/lib/enigma2/python'.
[Enigma] DVB API version 5, DVB API version minor 11.
[Enigma] Enigma debug level 3.
[eDVBPESReader] Created. Opening demux
[eDVBPESReader] Created. Opening demux
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 305, in action
    return ActionMap.action(self, contexts, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 276, in action
    response = self.actions[action]()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 455, in okbuttonClick
    current[WIDGET_MODULE]()
  File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 10, in __call__
    return self.fnc(*self.args + args, **newkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 487, in openSetup
    self.session.openWithCallback(self.menuClosed, Setup, dialog)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 162, in openWithCallback
    dialog = self.open(screen, *arguments, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/StartEnigma.py", line 173, in open
    dialog = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/StartEnigma.py", line 112, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/StartEnigma.py", line 134, in doInstantiateDialog
    dialog = screen(self, *arguments, **kwargs)  # Create dialog.
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Screens/Setup.py", line 76, in __init__
    self.createSetup()
  File "/usr/lib/enigma2/python/Screens/Setup.py", line 109, in createSetup
    self.addItems(setup)
  File "/usr/lib/enigma2/python/Screens/Setup.py", line 138, in addItems
    self.addItem(element)
  File "/usr/lib/enigma2/python/Screens/Setup.py", line 154, in addItem
    item = eval(element.text) if element.text else ""
           ^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/usr/lib/enigma2/python/Components/config.py", line 2101, in __getattr__
    raise AttributeError(name)
AttributeError: lcd_powerled
[ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap object at 0xaf0fae90>>,('OkCancelActions', 'ok')) failed)
```

**Comment by jbleyel** [comment]
Please provide more info:
* Boxtype
* How to reproduce
* Do you have `/proc/stb/power/powerled`

**Comment by GhostofGeeeee** [comment]
> Do you have /proc/stb/power/powerled?

Yes.

> Boxtype?

Multibox(No Lcd) -->
[detected != True](https://github.com/openatv/enigma2/blob/ff462270082f9bb2ae7fc25de73569fdd655aa56/lib/python/Components/Lcd.py#L274C15-L274C15)

> How to reproduce?

Menu -> Settings -> Usage & GUI -> Display Settings -> Crash
