### ISSUE TITLE
Oscam log lockup

### ISSUE THREAD

**Issue by AbuBaniaz** [openatv/enigma2#3460]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
This is 7.5, 29/11/2024 

**Describe the bug / Actual behaviour:**
[[A clear and concise description of what the bug is.]]
I go to oscam info and show log. There is an issue with oscam owif starting up, I press blue to show the log even though it says no log found. I am then trapped and locked and cant exit. init 4  then init 3 to restart

E2 log shows:
```
01:16:59.4583 Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
          File "/usr/lib/python3.12/threading.py", line 1012, in run
          File "/usr/lib/python3.12/site-packages/twisted/_threads/_threadworker.py", line 49, in work
          File "/usr/lib/python3.12/site-packages/twisted/_threads/_team.py", line 192, in doWork
        --- <exception caught here> ---
          File "/usr/lib/python3.12/site-packages/twisted/python/threadpool.py", line 269, in inContext
          File "/usr/lib/python3.12/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
          File "/usr/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
          File "/usr/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
          File "/usr/lib/enigma2/python/Screens/OScamInfo.py", line 796, in displayLog
          File "/usr/lib/enigma2/python/StartEnigma.py", line 172, in open
            self.pushCurrent()
          File "/usr/lib/enigma2/python/StartEnigma.py", line 147, in pushCurrent
            self.execEnd(last=False)
          File "/usr/lib/enigma2/python/StartEnigma.py", line 103, in execEnd
            self.current_dialog.execEnd()
          File "/usr/lib/enigma2/python/Screens/Screen.py", line 91, in execEnd
        builtins.AttributeError: 'OSCamInfoLog' object has no attribute 'activeComponents'
```
**Expected behaviour:**
[[A clear and concise description of what you expected to happen.]]
I should be able to exit out of the screen.

**Has this issue started to happen just recently?**
If yes, roughly when did it last work fine for you?
Not sure when it started.

**To reproduce:**
Blue > Softcam > Oscam information > Blue (show log) 

You are then trapped in the screen and cannot exit

**Screenshots**
Screenshots are incredibly helpful; if possible, please attach to help explain your problem.

**Image/Box Model (please complete the following information):**
 - Version: 7.5
-  Date: 2024.11.29
 - BoxModel: [vu duo 4k]

**Additional context**
E2 log attached

[192.168.1.179-20241130-011540.log.txt](https://github.com/user-attachments/files/17963779/192.168.1.179-20241130-011540.log.txt)

**Comment by MrServo** [comment]
Unfortunately, the error could not be reproduced, but the message box output could have a negative impact here. This output has now been routed to the log text...

**Comment by AbuBaniaz** [comment]
If oscam is running fine and it generates a log, the problem will not occur.

**Comment by AbuBaniaz** [comment]
Thanks for fixing.
